### ISSUE TITLE
[Cron] Infinite loop

### ISSUE THREAD

**Issue by george1604** [Newsman/Magento2-Newsman#1]
Hello,

There is an infinite loop inside module's cron (https://github.com/Newsman/Magento2-Newsman/blob/master/app/code/Dazoot/Newsman/Cron/Cron.php#L105). If there are more than 9999 subscribers in a customer group, the infinite loop triggers and it generates infinite number of files that are sent to Newsman. This issue also generates high outbound traffic and it is reflected in the Cloud Provider's bill.

Best,
George

**Comment by lucianfcorodeanu** [comment]
Hello. We will look and fix this as soon as possible.

Thanks
