### ISSUE TITLE
Cron failing 

### ISSUE THREAD

**Issue by patruvlad** [Newsman/Magento2-Newsman#4]
Cronjob not running as expected in magento 2.4.7 with the following error:
`main.CRITICAL: InvalidArgumentException: Incorrect theme identification key in /var/www/html/vendor/magento/framework/View/Design/Theme/FlyweightFactory.php:60
Stack trace:
#0 /var/www/html/vendor/magento/module-theme/Model/View/Design.php(153): Magento\Framework\View\Design\Theme\FlyweightFactory->create(NULL, 'crontab')
#1 /var/www/html/vendor/magento/module-theme/Model/View/Design.php(217): Magento\Theme\Model\View\Design->setDesignTheme(NULL)
#2 /var/www/html/vendor/magento/framework/App/Area.php(260): Magento\Theme\Model\View\Design->setDefaultDesignTheme()
#3 /var/www/html/vendor/magento/framework/App/Area.php(218): Magento\Framework\App\Area->_initDesign()
#4 /var/www/html/vendor/magento/framework/App/Area.php(140): Magento\Framework\App\Area->_loadPart('design')
#5 /var/www/html/vendor/magento/framework/View/DesignLoader.php(54): Magento\Framework\App\Area->load('design')
#6 /var/www/html/vendor/magento/module-theme/Plugin/LoadDesignPlugin.php(53): Magento\Framework\View\DesignLoader->load()
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Theme\Plugin\LoadDesignPlugin->beforeExecute(Object(Dazoot\Newsman\Cron\Cron\Interceptor), Object(Magento\Cron\Model\Schedule))
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Dazoot\Newsman\Cron\Cron\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Cron\Model\Schedule))
#9 /var/www/html/generated/code/Dazoot/Newsman/Cron/Cron/Interceptor.php(23): Dazoot\Newsman\Cron\Cron\Interceptor->___callPlugins('execute', Array, Array)
#10 [internal function]: Dazoot\Newsman\Cron\Cron\Interceptor->execute(Object(Magento\Cron\Model\Schedule))
#11 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(381): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(904): Magento\Cron\Observer\ProcessCronQueueObserver->_runJob(1726931760, 1726931762, Array, Object(Magento\Cron\Model\Schedule), 'default')
#13 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(865): Magento\Cron\Observer\ProcessCronQueueObserver->tryRunJob(1726931760, 1726931762, Array, Object(Magento\Cron\Model\Schedule), 'default')
#14 /var/www/html/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php(297): Magento\Cron\Observer\ProcessCronQueueObserver->processPendingJobs('default', Array, 1726931762)
#15 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Cron\Observer\ProcessCronQueueObserver->execute(Object(Magento\Framework\Event\Observer))
#16 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Cron\Observer\ProcessCronQueueObserver), Object(Magento\Framework\Event\Observer))
#17 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#18 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(105): Magento\Framework\Event\Manager->dispatch('default', Array)
#19 /var/www/html/vendor/magento/framework/App/Cron.php(86): Magento\Framework\Event\Manager\Proxy->dispatch('default')
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Cron->launch()
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Cron\Interceptor->___callParent('launch', Array)
#22 /var/www/html/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Cron\Interceptor->Magento\Framework\Interception\{closure}()
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch(Object(Magento\Framework\App\Cron\Interceptor), Object(Closure))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Cron\Interceptor->Magento\Framework\Interception\{closure}()
#25 /var/www/html/generated/code/Magento/Framework/App/Cron/Interceptor.php(23): Magento\Framework\App\Cron\Interceptor->___callPlugins('launch', Array, NULL)
#26 /var/www/html/vendor/magento/module-cron/Console/Command/CronCommand.php(140): Magento\Framework\App\Cron\Interceptor->launch()
#27 /var/www/html/vendor/symfony/console/Command/Command.php(326): Magento\Cron\Console\Command\CronCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cron\Console\Command\CronCommand\Interceptor->___callParent('run', Array)
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cron\Console\Command\CronCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/generated/code/Magento/Cron/Console/Command/CronCommand/Interceptor.php(77): Magento\Cron\Console\Command\CronCommand\Interceptor->___callPlugins('run', Array, Array)
#32 /var/www/html/vendor/symfony/console/Application.php(1078): Magento\Cron\Console\Command\CronCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Cron\Console\Command\CronCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/html/vendor/magento/framework/Console/Cli.php(118): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/html/vendor/symfony/console/Application.php(175): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#37 {main} [] []
`
This is due to the fact that Cron class extends Magento\Backend\App\Action . Cron classes whould be independent and not extend other classes.

**Comment by ilkadintelligence** [comment]
Fixed, Cron doesn't extend anymore
